ARG hadoop_version=3.2.0

FROM crs4/datanode:${hadoop_version}-ubuntu
RUN apt-get -y update && apt-get -y install --no-install-recommends \
      jsvc \
      libcap2 \
    && apt-get clean && rm -rf /var/lib/apt-lists/* /tmp/* /var/tmp/* \
    && echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >>/etc/profile.d/jsvc.sh \
    && echo "export JSVC_HOME=/usr/bin" >>/etc/profile.d/hadoop.sh
ENV JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
ENV JSVC_HOME="/usr/bin"
